insert into DEPARTMENT_INFO (CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, DEPARTMENT_CODE, DEPARTMENT_NAME)
values
    ('SYSTEM', CURRENT_TIMESTAMP(), 'SYSTEM', CURRENT_TIMESTAMP(), '1', '总公司'),
    ('SYSTEM', CURRENT_TIMESTAMP(), 'SYSTEM', CURRENT_TIMESTAMP(), '101', '北京分公司'),
    ('SYSTEM', CURRENT_TIMESTAMP(), 'SYSTEM', CURRENT_TIMESTAMP(), '102', '上海分公司'),
    ('SYSTEM', CURRENT_TIMESTAMP(), 'SYSTEM', CURRENT_TIMESTAMP(), '103', '广州分公司'),
    ('SYSTEM', CURRENT_TIMESTAMP(), 'SYSTEM', CURRENT_TIMESTAMP(), '104', '深圳分公司'),
    ('SYSTEM', CURRENT_TIMESTAMP(), 'SYSTEM', CURRENT_TIMESTAMP(), '105', '重庆分公司'),
    ('SYSTEM', CURRENT_TIMESTAMP(), 'SYSTEM', CURRENT_TIMESTAMP(), '106', '四川分公司'),
    ('SYSTEM', CURRENT_TIMESTAMP(), 'SYSTEM', CURRENT_TIMESTAMP(), '107', '山西分公司'),
    ('SYSTEM', CURRENT_TIMESTAMP(), 'SYSTEM', CURRENT_TIMESTAMP(), '108', '河北分公司'),
    ('SYSTEM', CURRENT_TIMESTAMP(), 'SYSTEM', CURRENT_TIMESTAMP(), '109', '河南分公司'),
    ('SYSTEM', CURRENT_TIMESTAMP(), 'SYSTEM', CURRENT_TIMESTAMP(), '110', '陕西分公司');