-- DROP TABLE IF EXISTS DEPARTMENT_INFO;

CREATE TABLE DEPARTMENT_INFO (
   ID                           INT          NOT NULL AUTO_INCREMENT,
   CREATED_BY                   VARCHAR(20)  NOT NULL,
   CREATED_DATE                 TIMESTAMP    NOT NULL,
   UPDATED_BY                   VARCHAR(20)  NOT NULL,
   UPDATED_DATE                 TIMESTAMP    NOT NULL,
   DEPARTMENT_CODE              VARCHAR(10)  NOT NULL,
   DEPARTMENT_NAME              VARCHAR(50)  NOT NULL,
   PRIMARY KEY (ID),
   UNIQUE KEY (DEPARTMENT_CODE),
   KEY (UPDATED_DATE)
);